// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIaMXjtu3S76PdwzAzs1DKGObCGrz0FU0',
    appId: '1:590591410897:web:98be6a1579768dbe193bf0',
    messagingSenderId: '590591410897',
    projectId: 'ubixstar-sarthak-sub',
    authDomain: 'ubixstar-sarthak-sub.firebaseapp.com',
    storageBucket: 'ubixstar-sarthak-sub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rkd7lsMK2cJjPETUfFzfyLggKh9Y3mo',
    appId: '1:590591410897:android:5eb62c2778010a3d193bf0',
    messagingSenderId: '590591410897',
    projectId: 'ubixstar-sarthak-sub',
    storageBucket: 'ubixstar-sarthak-sub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rt5onl4vIB2MVSt1dFpQEqBf3MQO5BQ',
    appId: '1:590591410897:ios:3c50b3bd3c780df8193bf0',
    messagingSenderId: '590591410897',
    projectId: 'ubixstar-sarthak-sub',
    storageBucket: 'ubixstar-sarthak-sub.appspot.com',
    iosBundleId: 'com.example.ubixstarassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rt5onl4vIB2MVSt1dFpQEqBf3MQO5BQ',
    appId: '1:590591410897:ios:6d20b7f6a1dca68d193bf0',
    messagingSenderId: '590591410897',
    projectId: 'ubixstar-sarthak-sub',
    storageBucket: 'ubixstar-sarthak-sub.appspot.com',
    iosBundleId: 'com.example.ubixstarassignment.RunnerTests',
  );
}
